version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warepulse-multi
    volumes:
      - mysql-data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  config-service:
    build: ./config-service
    ports:
      - 8888:8888
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PRIVATE_KEY=${PRIVATE_KEY}

  apigateway-service:
    build: ./apigateway-service
    container_name: apigateway-service
    ports:
      - "8080:8080"
    depends_on:
      - warepulse
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  service-discovery:
    build: ./service-discovery
    ports:
      - "8761:8761"

  warepulse:
    build: ./warepulse
    container_name: warepulse
    depends_on:
      - service-discovery
      - config-service
      - mysql
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod

#  inventory-service:
#    build: ./inventory-service
#    container_name: inventory-service
#    depends_on:
#      - mysql
#      - kafka
#    environment:
#      SPRING_PROFILES_ACTIVE: docker





volumes:
  mysql-data: